# Generated by Django 6.0.1 on 2026-01-11 20:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Назва"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Первинний"),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Колір НЕХ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Колір",
                "verbose_name_plural": "Кольори",
                "ordering": ["name"],
            },
        ),
    ]
